INDEX_HTML = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CoA Raid Intelligence</title>
<style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#131b2f;--line:#2a3754;--text:#edf2ff;--muted:#9ba9c5;--accent:#7c9cff;--ok:#72d6a0;--danger:#ff7f91;--warn:#ffd37a;--soft:#0d1528}
*{box-sizing:border-box}
body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:linear-gradient(140deg,#08101f,#111a31);color:var(--text)}
header{padding:18px 24px;border-bottom:1px solid var(--line);background:#0a1122}
h1{margin:0 0 4px}.muted{color:var(--muted)}
main{max-width:1700px;margin:auto;padding:18px;display:grid;grid-template-columns:minmax(760px,1fr) minmax(360px,420px);gap:16px;align-items:start}
.panel,.section-card{background:var(--panel);border:1px solid var(--line);border-radius:14px}
.toolbar{padding:12px;display:flex;flex-wrap:wrap;gap:10px;align-items:end;border-bottom:1px solid var(--line)}
label{display:grid;gap:4px;color:var(--muted);font-size:12px}
select,input,button{border:1px solid var(--line);border-radius:8px;background:var(--soft);color:var(--text);padding:8px}
button{background:var(--accent);color:#081020;font-weight:700;cursor:pointer}button:disabled{opacity:.55;cursor:not-allowed}.danger{background:var(--danger)}
table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid var(--line);text-align:left}th{color:var(--muted);font-size:12px;position:sticky;top:0;background:var(--panel);z-index:1}td input,td select{width:100%}tr.inactive{display:none}
.table-scroll{overflow:auto;max-height:calc(100vh - 175px)}
.summary{display:grid;gap:10px;align-self:start}.summary-shell{padding:12px;display:grid;gap:12px}
.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.metric{padding:10px;background:var(--soft);border:1px solid var(--line);border-radius:10px}.metric strong{display:block;font-size:24px;color:var(--ok)}.metric small{color:var(--muted)}
.coverage-bar{height:8px;background:#09101e;border-radius:8px;overflow:hidden;border:1px solid var(--line)}.coverage-bar span{display:block;height:100%;background:var(--ok);width:0}
.status{min-height:18px;color:var(--ok);font-size:13px}.errors{color:var(--danger);font-size:13px}.note{font-size:11px;color:var(--muted)}
details.section-card{overflow:hidden}details.section-card>summary{list-style:none;display:flex;justify-content:space-between;align-items:center;gap:8px;padding:11px 12px;cursor:pointer;font-weight:700}details.section-card>summary::-webkit-details-marker{display:none}details.section-card>summary::after{content:'▾';color:var(--muted)}details.section-card:not([open])>summary::after{content:'▸'}
.section-content{padding:0 12px 12px}.section-head{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px}.section-count{font-size:11px;color:var(--muted)}
.filter-row{display:flex;flex-wrap:wrap;gap:6px}.filter-button{padding:5px 9px;background:var(--soft);color:var(--muted);font-weight:600}.filter-button.active{background:var(--accent);color:#081020}.secondary-button{background:var(--soft);color:var(--text)}
.saved,.advisor,.missing{display:grid;gap:7px}.saved button{background:var(--soft);color:var(--text);text-align:left}.saved button.current{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent) inset}
.advisor-card,.effect-row{background:var(--soft);border:1px solid var(--line);border-radius:9px;padding:9px}.advisor-card strong{color:var(--accent)}.advisor-meta{margin:4px 0;color:var(--muted);font-size:12px}.advisor-effects{margin:7px 0 9px;padding-left:18px;font-size:12px}.advisor-effects li{margin:3px 0}.apply-advisor{width:100%;padding:7px}
.effect-row{font-size:12px}.priority-critical{border-left:3px solid var(--danger)}.priority-important{border-left:3px solid var(--warn)}.priority-optional{border-left:3px solid var(--muted)}
.diagnostics{white-space:pre-wrap;font:12px Consolas,monospace;background:#09101e;border:1px solid var(--line);border-radius:8px;padding:9px;max-height:280px;overflow:auto;color:var(--warn)}
.inline-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.compact-box{background:var(--soft);border:1px solid var(--line);border-radius:9px;padding:9px}
@media(max-width:1050px){main{grid-template-columns:1fr}.table-scroll{max-height:none}.inline-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<header><h1>CoA Raid Intelligence</h1><div class="muted">Локальный конструктор рейда • без Excel • DuckDB на этом компьютере</div></header>
<main>
<section class="panel">
<div class="toolbar">
<label>Название<input id="planName" value="Новый план"></label>
<label>Формат<select id="format"><option>FLEX</option><option>10</option><option selected>25</option><option>40</option></select></label>
<label>Размер<input id="target" type="number" min="1" max="40" value="25"></label>
<label>Дата<input id="raidDate" type="date"></label>
<label>Босс<input id="boss"></label>
<button id="newPlanButton">Новый</button><button id="savePlanButton">Сохранить</button><button id="deletePlanButton" class="danger">Удалить</button><span class="status" id="status"></span>
</div>
<div class="table-scroll"><table><thead><tr><th>#</th><th>Игрок</th><th>Класс</th><th>Спек</th><th>Роль</th><th>Lock</th></tr></thead><tbody id="slots"></tbody></table></div>
</section>
<aside class="summary">
<section class="panel summary-shell">
<div class="metric-grid"><div class="metric"><strong id="filled">0</strong><small>заполнено</small></div><div class="metric"><strong id="remaining">25</strong><small>осталось</small></div><div class="metric"><strong id="coveragePercent">0%</strong><small>покрытие</small></div></div>
<div class="coverage-bar"><span id="coverageBar"></span></div><div class="note" id="coverageMeta">0 из 45 эффектов</div>
<div class="inline-grid"><div class="compact-box"><b>Роли</b><div class="muted" id="roles">Нет заполненных ролей</div></div><div class="compact-box"><b>Проверки</b><div class="errors" id="errors">Ошибок нет</div></div></div>
</section>
<details class="section-card" id="missingSection" open><summary><span>Не закрыто</span><span class="section-count" id="missingCount">45</span></summary><div class="section-content"><div class="section-head"><div class="filter-row" id="missingFilters"><button class="filter-button active" data-filter="all">Все</button><button class="filter-button" data-filter="critical">Критичные</button><button class="filter-button" data-filter="important">Важные</button></div></div><div class="missing" id="missingEffects">Расчёт...</div><button id="showMoreMissing" class="secondary-button" hidden>Показать ещё</button></div></details>
<details class="section-card" id="advisorSection" open><summary><span>Советник Top-3</span><span class="section-count">по новым эффектам</span></summary><div class="section-content"><div class="advisor" id="recommendations">Расчёт...</div><div class="note">Сначала учитываются критичные эффекты, затем важные и опциональные. Ролевые квоты пока не применяются.</div></div></details>
<details class="section-card" id="savedSection" open><summary><span>Сохранённые планы</span><span class="section-count" id="savedCount">0</span></summary><div class="section-content"><div class="saved" id="savedPlans"></div></div></details>
<details class="section-card" id="diagnosticsSection"><summary><span>Диагностика</span><span class="section-count">API</span></summary><div class="section-content"><div class="diagnostics" id="diagnostics">Готово</div></div></details>
</aside>
</main>
<script>
const tbody=document.getElementById('slots'),format=document.getElementById('format'),target=document.getElementById('target');
let catalog={classes:[]},currentPlanId=null,timer,lastPreviewPayload=null,lastAnalytics=null,missingFilter='all',missingLimit=8;
for(let i=1;i<=40;i++)tbody.insertAdjacentHTML('beforeend',`<tr data-slot="${i}"><td>${i}</td><td><input class="player"></td><td><select class="class"></select></td><td><select class="spec"></select></td><td><input class="role" readonly></td><td><input class="locked" type="checkbox"></td></tr>`);
function summarizeForLog(url,data){
 if(url==='/api/plans/preview'&&data?.slots)return{plan_id:data.plan_id,plan_name:data.plan_name,raid_format:data.raid_format,target_size:data.target_size,filled_slots:data.filled_slots,remaining_slots:data.remaining_slots,role_counts:data.role_counts,validation_errors:data.validation_errors,coverage:{covered:data.coverage?.covered_effects,total:data.coverage?.total_effects,percent:data.coverage?.coverage_percent},recommendations:(data.recommendations||[]).map(x=>({candidate:`${x.class_name} — ${x.spec_name}`,new_effect_count:x.new_effect_count}))};
 if(url==='/api/catalog/class-specs'&&data?.classes)return{schema_version:data.schema_version,class_count:data.classes.length,entry_count:data.entry_count};
 if(url==='/api/plans'&&Array.isArray(data?.plans))return{count:data.plans.length,plans:data.plans.map(p=>({plan_id:p.plan_id?.slice(0,8),plan_name:p.plan_name,raid_format:p.raid_format,target_size:p.target_size}))};
 return data;
}
function logDiagnostic(message,data=null){const time=new Date().toLocaleTimeString();const extra=data?`\n${typeof data==='string'?data:JSON.stringify(data,null,2)}`:'';diagnostics.textContent=`[${time}] ${message}${extra}\n\n${diagnostics.textContent}`;console.log(message,data||'')}
async function apiFetch(url,options={}){logDiagnostic(`${options.method||'GET'} ${url}`);let response;try{response=await fetch(url,options)}catch(error){logDiagnostic(`Сетевая ошибка ${url}`,String(error));throw error}const requestId=response.headers.get('X-Request-ID')||'нет';let data=null;if(response.status!==204){const text=await response.text();try{data=text?JSON.parse(text):null}catch{data=text}}logDiagnostic(`${response.status} ${url} · request ${requestId}`,summarizeForLog(url,data));if(!response.ok){const detail=data?.detail;const message=typeof detail==='string'?detail:(detail?.message||data?.message||`HTTP ${response.status}`);const error=new Error(message);error.payload=data;error.requestId=requestId;error.status=response.status;throw error}return data}
function classOptions(value=''){return '<option value=""></option>'+catalog.classes.map(c=>`<option value="${c.code}" ${c.code===value?'selected':''}>${c.name}</option>`).join('')}
function syncSpecs(row,classCode='',specCode=''){const cls=catalog.classes.find(c=>c.code===classCode);row.querySelector('.spec').innerHTML='<option value=""></option>'+(cls?.specs||[]).map(s=>`<option value="${s.code}" ${s.code===specCode?'selected':''}>${s.name}</option>`).join('');row.querySelector('.role').value=(cls?.specs||[]).find(s=>s.code===specCode)?.role||''}
function requestBody(){return{plan_id:currentPlanId,plan_name:planName.value,raid_date:raidDate.value||null,boss_id:boss.value,raid_format:format.value,target_size:Number(target.value),slots:[...tbody.rows].map(r=>({slot_no:Number(r.dataset.slot),player_name:r.querySelector('.player').value,class_code:r.querySelector('.class').value,spec_code:r.querySelector('.spec').value,role:r.querySelector('.role').value,locked:r.querySelector('.locked').checked})).filter(x=>x.player_name||x.class_code||x.spec_code||x.locked)}}
function filteredMissing(){const missing=lastAnalytics?.coverage?.missing||[];if(missingFilter==='critical')return missing.filter(x=>x.priority==='Критично');if(missingFilter==='important')return missing.filter(x=>x.priority==='Важно');return missing}
function renderMissing(){const items=filteredMissing();missingCount.textContent=String(items.length);const visible=items.slice(0,missingLimit);missingEffects.innerHTML=visible.map(x=>`<div class="effect-row ${x.priority==='Критично'?'priority-critical':x.priority==='Важно'?'priority-important':'priority-optional'}"><b>${x.name}</b><br><span class="muted">${x.priority} · ${x.category}</span></div>`).join('')||'<span class="muted">Все эффекты выбранной группы закрыты</span>';showMoreMissing.hidden=items.length<=missingLimit;showMoreMissing.textContent=`Показать ещё (${items.length-missingLimit})`}
function recommendationCard(x,index){const effects=x.new_effects.map(e=>`<li><b>${e.name}</b> <span class="muted">${e.priority}</span></li>`).join('');return `<div class="advisor-card"><strong>${index+1}. ${x.class_name} — ${x.spec_name}</strong><div class="advisor-meta">${x.role} · закрывает ${x.new_effect_count} новых эффектов</div><div class="note">${x.explanation}</div><ul class="advisor-effects">${effects}</ul><button class="apply-advisor" data-class-code="${x.class_code}" data-spec-code="${x.spec_code}">Добавить в свободный слот</button></div>`}
function renderAnalytics(data){lastAnalytics=data;const c=data.coverage;coveragePercent.textContent=`${c.coverage_percent}%`;coverageBar.style.width=`${c.coverage_percent}%`;coverageMeta.textContent=`${c.covered_effects} из ${c.total_effects} эффектов · не закрыто ${c.missing_effects}`;missingLimit=8;renderMissing();recommendations.innerHTML=(data.recommendations||[]).map(recommendationCard).join('')||'<span class="muted">Нет кандидатов с новым покрытием</span>'}
function firstFreeActiveRow(){return [...tbody.rows].find(row=>!row.classList.contains('inactive')&&!row.querySelector('.player').value.trim()&&!row.querySelector('.class').value&&!row.querySelector('.spec').value)}
function applyRecommendation(classCode,specCode){const row=firstFreeActiveRow();if(!row){status.textContent='Нет свободного активного слота';return}row.querySelector('.class').innerHTML=classOptions(classCode);syncSpecs(row,classCode,specCode);row.scrollIntoView({behavior:'smooth',block:'center'});row.querySelector('.player').focus();status.textContent=`Слот ${row.dataset.slot}: укажите игрока для рекомендованного спека`;resetPreviewCache();schedule()}
async function recalcPlan(force=false){const body=requestBody(),serialized=JSON.stringify(body);if(!force&&serialized===lastPreviewPayload)return;lastPreviewPayload=serialized;try{const data=await apiFetch('/api/plans/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:serialized});data.slots.forEach(s=>{const r=tbody.querySelector(`[data-slot="${s.slot_no}"]`);r.classList.toggle('inactive',!s.active);r.querySelector('.role').value=s.role});filled.textContent=data.filled_slots;remaining.textContent=data.remaining_slots;roles.innerHTML=Object.entries(data.role_counts).map(([k,v])=>`${k}: <b>${v}</b>`).join('<br>')||'Нет заполненных ролей';errors.innerHTML=data.validation_errors.join('<br>')||'Ошибок нет';renderAnalytics(data)}catch(error){lastPreviewPayload=null;errors.textContent=`${error.message} (${error.status||'network'}, request ${error.requestId||'нет'})`}}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>recalcPlan(),180)}
function syncFormat(){const fixed={'10':10,'25':25,'40':40};if(fixed[format.value]){target.value=fixed[format.value];target.disabled=true}else target.disabled=false;schedule()}
async function loadCatalog(){catalog=await apiFetch('/api/catalog/class-specs');[...tbody.rows].forEach(r=>{r.querySelector('.class').innerHTML=classOptions()})}
function markCurrentPlan(){[...savedPlans.querySelectorAll('button[data-id]')].forEach(button=>button.classList.toggle('current',button.dataset.id===currentPlanId))}
function resetPreviewCache(){lastPreviewPayload=null}
function clearCurrentPlan(){currentPlanId=null;planName.value='Новый план';raidDate.value='';boss.value='';format.value='25';target.value=25;[...tbody.rows].forEach(r=>{r.querySelector('.player').value='';r.querySelector('.class').innerHTML=classOptions();syncSpecs(r);r.querySelector('.locked').checked=false});resetPreviewCache();syncFormat();status.textContent='Новый план';markCurrentPlan();logDiagnostic('Создан новый локальный план')}
async function persistCurrentPlan(){const updating=Boolean(currentPlanId);status.textContent=updating?'Обновление...':'Сохранение...';try{const data=await apiFetch('/api/plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(requestBody())});currentPlanId=data.plan_id;resetPreviewCache();status.textContent=data.action==='updated'?`Обновлено: ${data.plan_id.slice(0,8)}`:`Создано: ${data.plan_id.slice(0,8)}`;await refreshSavedPlans();markCurrentPlan()}catch(error){status.textContent=`Ошибка: ${error.message}`;const validation=error.payload?.detail?.validation_errors||[];errors.innerHTML=[`Сохранение не выполнено: ${error.message}`,...validation].join('<br>')+`<br>HTTP ${error.status||'network'}, request ${error.requestId||'нет'}`}}
async function refreshSavedPlans(){try{const data=await apiFetch('/api/plans');savedCount.textContent=String(data.plans.length);savedPlans.innerHTML=data.plans.map(p=>`<button data-id="${p.plan_id}" class="${p.plan_id===currentPlanId?'current':''}">${p.plan_name||'Без названия'} · ${p.raid_format}/${p.target_size}<br><span class="muted">${p.plan_id.slice(0,8)} · ${p.updated_at||''}</span></button>`).join('')||'<span class="muted">Планов нет</span>'}catch(error){savedPlans.innerHTML=`<span class="errors">${error.message}</span>`}}
async function openSavedPlan(id){status.textContent='Открытие...';try{const p=await apiFetch(`/api/plans/${id}`);currentPlanId=p.plan_id;planName.value=p.plan_name;raidDate.value=p.raid_date||'';boss.value=p.boss_id||'';format.value=p.raid_format;target.value=p.target_size;[...tbody.rows].forEach(r=>{const s=p.slots.find(x=>x.slot_no===Number(r.dataset.slot))||{};r.querySelector('.player').value=s.player_name||'';r.querySelector('.class').innerHTML=classOptions(s.class_code||'');syncSpecs(r,s.class_code||'',s.spec_code||'');r.querySelector('.locked').checked=!!s.locked});resetPreviewCache();syncFormat();markCurrentPlan();status.textContent=`Открыт: ${p.plan_id.slice(0,8)}`}catch(error){status.textContent=`Ошибка открытия: ${error.message}`}}
async function removeCurrentPlan(){if(!currentPlanId){status.textContent='Нет открытого плана';return}const deleting=currentPlanId;status.textContent='Удаление...';try{await apiFetch(`/api/plans/${deleting}`,{method:'DELETE'});clearCurrentPlan();await refreshSavedPlans();status.textContent=`Удалён: ${deleting.slice(0,8)}`}catch(error){status.textContent=`Ошибка удаления: ${error.message}`}}
format.addEventListener('change',syncFormat);target.addEventListener('input',schedule);tbody.addEventListener('input',schedule);tbody.addEventListener('change',e=>{const r=e.target.closest('tr');if(e.target.classList.contains('class'))syncSpecs(r,e.target.value);if(e.target.classList.contains('spec'))syncSpecs(r,r.querySelector('.class').value,e.target.value);schedule()});savedPlans.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(b)openSavedPlan(b.dataset.id)});missingFilters.addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;missingFilter=b.dataset.filter;missingLimit=8;[...missingFilters.querySelectorAll('button')].forEach(x=>x.classList.toggle('active',x===b));renderMissing()});showMoreMissing.addEventListener('click',()=>{missingLimit+=8;renderMissing()});recommendations.addEventListener('click',e=>{const b=e.target.closest('button.apply-advisor');if(b)applyRecommendation(b.dataset.classCode,b.dataset.specCode)});document.getElementById('newPlanButton').addEventListener('click',clearCurrentPlan);document.getElementById('savePlanButton').addEventListener('click',persistCurrentPlan);document.getElementById('deletePlanButton').addEventListener('click',removeCurrentPlan);
(async()=>{try{await loadCatalog();clearCurrentPlan();await refreshSavedPlans()}catch(error){status.textContent=`Ошибка запуска: ${error.message}`;logDiagnostic('Инициализация не выполнена',error.payload||String(error))}})();
</script>
</body>
</html>'''
