INDEX_HTML = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CoA Raid Intelligence</title>
<style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#131b2f;--line:#2a3754;--text:#edf2ff;--muted:#9ba9c5;--accent:#7c9cff;--ok:#72d6a0;--danger:#ff7f91}*{box-sizing:border-box}body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:linear-gradient(140deg,#08101f,#111a31);color:var(--text)}header{padding:18px 24px;border-bottom:1px solid var(--line);background:#0a1122}h1{margin:0 0 4px}.muted{color:var(--muted)}main{max-width:1600px;margin:auto;padding:18px;display:grid;grid-template-columns:minmax(760px,1fr) 330px;gap:16px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px}.toolbar{padding:12px;display:flex;flex-wrap:wrap;gap:10px;align-items:end;border-bottom:1px solid var(--line)}label{display:grid;gap:4px;color:var(--muted);font-size:12px}select,input,button{border:1px solid var(--line);border-radius:8px;background:#0d1528;color:var(--text);padding:8px}button{background:var(--accent);color:#081020;font-weight:700;cursor:pointer}.danger{background:var(--danger)}table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid var(--line);text-align:left}th{color:var(--muted);font-size:12px}td input,td select{width:100%}tr.inactive{display:none}.summary{padding:14px;display:grid;gap:12px;height:max-content}.metric{padding:12px;background:#0d1528;border:1px solid var(--line);border-radius:10px}.metric strong{display:block;font-size:26px;color:var(--ok)}.errors{color:var(--danger);font-size:13px}.saved{display:grid;gap:6px}.saved button{background:#0d1528;color:var(--text);text-align:left}.status{min-height:18px;color:var(--ok);font-size:13px}@media(max-width:1050px){main{grid-template-columns:1fr}}
</style></head><body>
<header><h1>CoA Raid Intelligence</h1><div class="muted">Локальный конструктор рейда • без Excel • DuckDB на этом компьютере</div></header>
<main><section class="panel"><div class="toolbar">
<label>Название<input id="planName" value="Новый план"></label><label>Формат<select id="format"><option>FLEX</option><option>10</option><option selected>25</option><option>40</option></select></label><label>Размер<input id="target" type="number" min="1" max="40" value="25"></label><label>Дата<input id="raidDate" type="date"></label><label>Босс<input id="boss"></label><button id="newPlan">Новый</button><button id="savePlan">Сохранить</button><button id="deletePlan" class="danger">Удалить</button><span class="status" id="status"></span>
</div><div style="overflow:auto;max-height:calc(100vh - 175px)"><table><thead><tr><th>#</th><th>Игрок</th><th>Класс</th><th>Спек</th><th>Роль</th><th>Lock</th></tr></thead><tbody id="slots"></tbody></table></div></section>
<aside class="panel summary"><div class="metric"><strong id="filled">0</strong><span class="muted">заполнено</span></div><div class="metric"><strong id="remaining">25</strong><span class="muted">осталось</span></div><div><b>Роли</b><div class="muted" id="roles">Нет заполненных ролей</div></div><div><b>Проверки</b><div class="errors" id="errors">Ошибок нет</div></div><div><b>Сохранённые планы</b><div class="saved" id="savedPlans"></div></div></aside></main>
<script>
const tbody=document.getElementById('slots'),format=document.getElementById('format'),target=document.getElementById('target');let catalog={classes:[]},currentPlanId=null,timer;
for(let i=1;i<=40;i++)tbody.insertAdjacentHTML('beforeend',`<tr data-slot="${i}"><td>${i}</td><td><input class="player"></td><td><select class="class"></select></td><td><select class="spec"></select></td><td><input class="role" readonly></td><td><input class="locked" type="checkbox"></td></tr>`);
function classOptions(value=''){return '<option value=""></option>'+catalog.classes.map(c=>`<option value="${c.code}" ${c.code===value?'selected':''}>${c.name}</option>`).join('')}
function syncSpecs(row,classCode='',specCode=''){const cls=catalog.classes.find(c=>c.code===classCode);row.querySelector('.spec').innerHTML='<option value=""></option>'+(cls?.specs||[]).map(s=>`<option value="${s.code}" ${s.code===specCode?'selected':''}>${s.name}</option>`).join('');row.querySelector('.role').value=(cls?.specs||[]).find(s=>s.code===specCode)?.role||''}
function requestBody(){return{plan_id:currentPlanId,plan_name:planName.value,raid_date:raidDate.value||null,boss_id:boss.value,raid_format:format.value,target_size:Number(target.value),slots:[...tbody.rows].map(r=>({slot_no:Number(r.dataset.slot),player_name:r.querySelector('.player').value,class_code:r.querySelector('.class').value,spec_code:r.querySelector('.spec').value,role:r.querySelector('.role').value,locked:r.querySelector('.locked').checked})).filter(x=>x.player_name||x.class_code||x.spec_code||x.locked)}}
async function recalc(){const res=await fetch('/api/plans/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(requestBody())});const data=await res.json();if(!res.ok){errors.textContent=data.detail?.[0]?.msg||'Ошибка расчёта';return}data.slots.forEach(s=>{const r=tbody.querySelector(`[data-slot="${s.slot_no}"]`);r.classList.toggle('inactive',!s.active);r.querySelector('.role').value=s.role});filled.textContent=data.filled_slots;remaining.textContent=data.remaining_slots;roles.innerHTML=Object.entries(data.role_counts).map(([k,v])=>`${k}: <b>${v}</b>`).join('<br>')||'Нет заполненных ролей';errors.innerHTML=data.validation_errors.join('<br>')||'Ошибок нет'}
function schedule(){clearTimeout(timer);timer=setTimeout(recalc,180)}
function syncFormat(){const fixed={'10':10,'25':25,'40':40};if(fixed[format.value]){target.value=fixed[format.value];target.disabled=true}else target.disabled=false;schedule()}
async function loadCatalog(){catalog=await (await fetch('/api/catalog/class-specs')).json();[...tbody.rows].forEach(r=>{r.querySelector('.class').innerHTML=classOptions()})}
function clearPlan(){currentPlanId=null;planName.value='Новый план';raidDate.value='';boss.value='';format.value='25';target.value=25;[...tbody.rows].forEach(r=>{r.querySelector('.player').value='';r.querySelector('.class').innerHTML=classOptions();syncSpecs(r);r.querySelector('.locked').checked=false});syncFormat();status.textContent='Новый план'}
async function savePlan(){const res=await fetch('/api/plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(requestBody())});const data=await res.json();if(!res.ok){status.textContent='Ошибка сохранения';return}currentPlanId=data.plan_id;status.textContent='Сохранено';await refreshPlans()}
async function refreshPlans(){const data=await (await fetch('/api/plans')).json();savedPlans.innerHTML=data.plans.map(p=>`<button data-id="${p.plan_id}">${p.plan_name||'Без названия'} · ${p.raid_format}/${p.target_size}</button>`).join('')||'<span class="muted">Планов нет</span>'}
async function loadPlan(id){const p=await (await fetch(`/api/plans/${id}`)).json();currentPlanId=p.plan_id;planName.value=p.plan_name;raidDate.value=p.raid_date||'';boss.value=p.boss_id||'';format.value=p.raid_format;target.value=p.target_size;[...tbody.rows].forEach(r=>{const s=p.slots.find(x=>x.slot_no===Number(r.dataset.slot))||{};r.querySelector('.player').value=s.player_name||'';r.querySelector('.class').innerHTML=classOptions(s.class_code||'');syncSpecs(r,s.class_code||'',s.spec_code||'');r.querySelector('.locked').checked=!!s.locked});syncFormat();status.textContent='План открыт'}
async function deletePlan(){if(!currentPlanId)return;await fetch(`/api/plans/${currentPlanId}`,{method:'DELETE'});clearPlan();await refreshPlans()}
format.addEventListener('change',syncFormat);target.addEventListener('input',schedule);tbody.addEventListener('input',schedule);tbody.addEventListener('change',e=>{const r=e.target.closest('tr');if(e.target.classList.contains('class'))syncSpecs(r,e.target.value);if(e.target.classList.contains('spec'))syncSpecs(r,r.querySelector('.class').value,e.target.value);schedule()});savedPlans.addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(b)loadPlan(b.dataset.id)});newPlan.onclick=clearPlan;savePlan.onclick=savePlan;deletePlan.onclick=deletePlan;
(async()=>{await loadCatalog();clearPlan();await refreshPlans()})();
</script></body></html>'''
